version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:${NGINX_PORT:-80}:80"

  php-fpm:
    build:
      context: .
    user: 1000:1000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@postgres/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=utf8
      - APP_ENV=${APP_ENV:-dev}
      - APP_SECRET=${APP_SECRET:-secret}
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
